steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - enrich_ga4_data
  - --region=europe-west3
  - --source=.
  - --trigger-http
  - --runtime=nodejs20
  - --entry-point=enrich_ga4_data
  - --allow-unauthenticated
  - --gen2